Modified the HAS_UART configuration to reduce code size by undefining the printf function (a void initializion of the UART is needed to allow the linker to find the putchar function otherwise uart.o is not linked resulting in an undefined reference to putchar)